In [ ]:
                    # ---------------torch.nn module--------#
                     
# It is a core module of Pytorch which contain various function and class to build Neural Network.
    
# Key components of torch.nn module

# 1. Modules (Layers)
    # nn Module: The base class for all neural network modules.
    # Common layers: Includes layers like nn.Linear(Fully Connected Layer), nn.Conv2D (Convolution Layer), nn.LSTM (Recurrent Layer)

# 2. Activation Function:
    #  Function Like nn.Relu() , nn.Sigmoid(), nn.Softmax(), nn.Tanh() introduce nonlinearities to the model.
    # Allow it to learn complex pattern of Data

# 3. Loss Function
    # Provides loss function such as nn.BinaryCrossEntrophy, nn.MSEloss, nn.NLLLoss to calculate the difference between predited value and actual value.

# 4. Container Modules:
    # nn.Sequential(): A sequential Container to stack layers in order. 

# 5. Regularization and Dropout:
    # Layers like nn.Dropout() and nn.BatchNorm2D help to prevent overfitting and improve the model performances.
    #

In [ ]:
            # -----------torch.optim Module---------#
             
# It is a module in Pytorch that provides various optimization tools which help to update the parameters based on loss of a model during training.

    # Its include common optimizer such as Adam, RSMprop, Stochastic Gradient Descent (SGD) and more.
    # It handles weight updates effectively and including additional features like learning rate scheduling and Weight Decay(Regularization).

# model.parameters method in PyTorch retrives an iterator all over the trainable parameters (weights and biases) in amodel.
# Parametrs: Weights and biases
# Optimizer use these parameters to claculate gradient and update them during training.

In [2]:
# Code  Example:

# Inport Required Libraries
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.model_selection import train_test_split

In [3]:
# Upload Data set
df=pd.read_csv('breast_cancer.csv')
df.head(4)

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300

In [4]:
# Drop the Id column
df=df.drop(columns='id')
df.head(2)

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.8,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.6,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.9,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.8,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902

In [5]:
# Extract Input and Oputput Value
X=df.iloc[:, 1:]
y=df.iloc[:, 0]

In [6]:
# Split the dataset into train and test set
X_train, X_test, y_train, y_test=train_test_split(
    X,y, test_size=0.2
)

In [7]:
# Scale the train data
scaler=StandardScaler()
X_train_scaled=scaler.fit_transform(X_train)
X_test_scaled=scaler.transform(X_test)

In [8]:
# Perform Label Encoding on Target Column
encoder=LabelEncoder()
y_train=encoder.fit_transform(y_train)
y_test=encoder.transform(y_test)

In [ ]:
# Convert numpy array to PyTorch tensor (float_32)
X_train_tensor = torch.from_numpy(X_train_scaled).float()
X_test_tensor = torch.from_numpy(X_test_scaled).float()

y_train_tensor = torch.from_numpy(y_train).float()
y_test_tensor = torch.from_numpy(y_test).float()

In [36]:
# Building the Neural Network using built-in nn.module

class MySimpleNN(nn.Module):

    def __init__(self, num_features):
        super().__init__()

        self.linear = nn.Linear(num_features, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, features):

        out = self.linear(features)
        out = self.sigmoid(out)

        return out

In [25]:
# Define Important parameter
learning_rate=0.1
epochs=25

In [ ]:
# Use Built-in loss function
loss_function=nn.BCELoss()

In [ ]:
# Create model
model = MySimpleNN(X_train_tensor.shape[1])

# Define Built-in optimizer
optimizer=torch.optim.SGD(model.parameters(), lr=learning_rate)

# Training loop
for epoch in range(epochs):

    # Forward pass
    y_pred = model(X_train_tensor)

    # Calculate loss
    loss = loss_function(y_pred, y_train_tensor.view(-1,1))

    # Clear Gradient
    optimizer.zero_grad()

    # Backward pass
    loss.backward()

    # Parameters update
    optimizer.step()

    # Zero gradients
    model.linear.weight.grad.zero_()
    model.linear.bias.grad.zero_()

    # Print loss
    print(f'Epoch: {epoch + 1}, Loss: {loss.item():.4f}')

Epoch: 1, Loss: 0.8140
Epoch: 2, Loss: 0.5709
Epoch: 3, Loss: 0.4524
Epoch: 4, Loss: 0.3869
Epoch: 5, Loss: 0.3450
Epoch: 6, Loss: 0.3156
Epoch: 7, Loss: 0.2935
Epoch: 8, Loss: 0.2761
Epoch: 9, Loss: 0.2619
Epoch: 10, Loss: 0.2502
Epoch: 11, Loss: 0.2401
Epoch: 12, Loss: 0.2314
Epoch: 13, Loss: 0.2238
Epoch: 14, Loss: 0.2171
Epoch: 15, Loss: 0.2110
Epoch: 16, Loss: 0.2056
Epoch: 17, Loss: 0.2006
Epoch: 18, Loss: 0.1961
Epoch: 19, Loss: 0.1919
Epoch: 20, Loss: 0.1880
Epoch: 21, Loss: 0.1845
Epoch: 22, Loss: 0.1811
Epoch: 23, Loss: 0.1780
Epoch: 24, Loss: 0.1751
Epoch: 25, Loss: 0.1724

In [35]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.5524776577949524